### PR TITLE
Issue144 async

### PR DESCRIPTION
**Pull request by ZenTauro**
Implementing async:
 - [x] `pacman-mirrors -f 0` async
 - [x] `pacman-mirrors -f x` when 5 < x < 15 it sometimes gets stuck 

```sh
$ make test &> test.log
python setup.py test
running test
running egg_info
writing pacman_mirrors.egg-info/PKG-INFO
writing dependency_links to pacman_mirrors.egg-info/dependency_links.txt
writing top-level names to pacman_mirrors.egg-info/top_level.txt
reading manifest file 'pacman_mirrors.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'man/pacman-mirrors.8'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'pacman_mirrors.egg-info/SOURCES.txt'
running build_ext
test_default_branch (tests.test_default_config.TestDefaultConfig)
TEST: config[branch] = stable ... ok
test_default_method (tests.test_default_config.TestDefaultConfig)
TEST: config[method] = rank ... ok
test_default_mirrordir (tests.test_default_config.TestDefaultConfig)
TEST: config[mirror_dir] = tests/mock/var/ ... ok
test_default_mirrorfile (tests.test_default_config.TestDefaultConfig)
TEST: config[mirror_file] = tests/mock/usr/mirrors.json ... ok
test_default_mirrorlist (tests.test_default_config.TestDefaultConfig)
TEST: config[mirror_list] = tests/mock/etc/mirrorlist ... ok
test_default_noupdate (tests.test_default_config.TestDefaultConfig)
TEST: config[no_update] = False ... ok
test_default_onlycountry (tests.test_default_config.TestDefaultConfig)
TEST: config[only_country] = [] ... ok
test_arg_fasttrack (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI fasttrack is 5 from ARG '-f 5' ... ok
test_arg_geoip (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI geoip is True from ARG '--geoip' ... ok
test_arg_interactive (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI interactive is true from ARG '-i' ... ok
test_arg_max_wait_time (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI max_wait_time is 5 from ARG '-t 5' ... ok
test_arg_method (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI config[method] from ARG '-m random' ... ok
test_arg_onlycountry (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI config[only_country] from ARG '-c France,Germany' ... ok
test_arg_quiet (tests.test_command_line_parse.TestCommandLineParse)
TEST: CLI quiet is True from ARG '-q' ... ok
test_txt_special_word_api (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD API ... ok
test_txt_special_word_branch (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD BRANCH ... ok
test_txt_special_word_country (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD COUNTRY ... ok
test_txt_special_word_file (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD FILE ... ok
test_txt_special_word_method (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD METHOD ... ok
test_txt_special_word_methods (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD METHODS ... ok
test_txt_special_word_misc (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD MISC ... ok
test_txt_special_word_number (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD NUMBER ... ok
test_txt_special_word_path (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD PATH ... ok
test_txt_special_word_prefix (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD PREFIX ... ok
test_txt_special_word_proto (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD PROTO ... ok
test_txt_special_word_seconds (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD SECONDS ... ok
test_txt_special_word_url (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD URL ... ok
test_txt_special_word_usage (tests.test_txt_special_words.TestTextSpecialWords)
TEST: txt SPECIAL WORD USAGE ... ok
test_txt_opt_country (tests.test_txt_options.TestTextOptions)
TEST: txt OPT_COUNTRY ... ok
test_txt_opt_random (tests.test_txt_options.TestTextOptions)
TEST: txt OPT_RANDOM ... ok
test_full_run_fasttrack (tests.test_pacman_mirrors.TestPacmanMirrors)
TEST: pacman-mirrors -f5 ... ok
test_full_run_random (tests.test_pacman_mirrors.TestPacmanMirrors)
TEST: pacman-mirrors -c all -m random ... ok
test_full_run_rank (tests.test_pacman_mirrors.TestPacmanMirrors)
TEST: pacman-mirrors -c all ... ok
test_txt_err_color (tests.test_txt_colors.TestTextColors)
TEST: txt ERR_CLR ... ok
test_txt_inf_color (tests.test_txt_colors.TestTextColors)
TEST: txt INF_CLR ... ok
test_txt_wrn_color (tests.test_txt_colors.TestTextColors)
TEST: txt WRN_COLOR ... ok
test_txt_houston (tests.test_txt_non_translatable.TestTextConstants)
TEST: txt HOUSTON ... ok
test_txt_override_opt (tests.test_txt_non_translatable.TestTextConstants)
TEST: txt OVERRIDE_OPT ... ok
test_txt_prefix_tip (tests.test_txt_non_translatable.TestTextConstants)
TEST: txt PREFIX_TIP ... ok
test_txt_repo_server (tests.test_txt_non_translatable.TestTextConstants)
TEST: txt REPO_SERVER ... ok
test_txt_reset_custom_file (tests.test_txt_non_translatable.TestTextConstants)
TEST: txt RESET_CUSTOM_FILE ... ok
test_initial_custom (tests.test_inital_values.TestInitialValues)
TEST: self.custom is False ... ok
test_initial_fasttrack (tests.test_inital_values.TestInitialValues)
TEST: self.fasttrack is False ... ok
test_initial_geoip (tests.test_inital_values.TestInitialValues)
TEST: self.geoip is False ... ok
test_initial_interactive (tests.test_inital_values.TestInitialValues)
TEST: self.interactive is False ... ok
test_initial_max_wait_time (tests.test_inital_values.TestInitialValues)
TEST: self.max_wait_time = 2 ... ok
test_initial_network (tests.test_inital_values.TestInitialValues)
TEST: self.network is True ... ok
test_initial_no_mirrorlist (tests.test_inital_values.TestInitialValues)
TEST: self.no_mirrorlist = False ... ok
test_initial_nodisplay (tests.test_inital_values.TestInitialValues)
TEST: self.no_display is False ... ok
test_initial_quiet (tests.test_inital_values.TestInitialValues)
TEST: self.quiet is False ... ok
test_initial_selected_countries (tests.test_inital_values.TestInitialValues)
TEST: self.selected_countries = [] ... ok
test_txt_lastsync_na (tests.test_txt_mirror_status.TestTextMirrorStatus)
TEST: txt LASTSYNC_NA ... ok
test_txt_lastsync_ok (tests.test_txt_mirror_status.TestTextMirrorStatus)
TEST: txt LASTSYNC_OK ... ok
test_txt_server_bad (tests.test_txt_mirror_status.TestTextMirrorStatus)
TEST: txt SERVER_BAD ... ok
test_txt_server_res (tests.test_txt_mirror_status.TestTextMirrorStatus)
TEST: txt SERVER_RES ... ok
test_txt_interactive_cancel (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE CANCEL ... ok
test_txt_interactive_confirm (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE CONFIRM ... ok
test_txt_interactive_confirm_selection (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE CONFIRM SELECTION ... ok
test_txt_interactive_country (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE COUNTRY ... ok
test_txt_interactive_last_sync (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE LAST SYNC ... ok
test_txt_interactive_list_title (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE LIST TITLE ... ok
test_txt_interactive_response (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE RESPONSE ... ok
test_txt_interactive_title (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE TITLE ... ok
test_txt_interactive_title_random (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE TITLE RANDOM ... ok
test_txt_interactive_url (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE URL ... ok
test_txt_interactive_use (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE USE ... ok
test_txt_interactive_use_these_mirrors (tests.test_txt_interactive_messages.TestTextInteractiveMessages)
TEST: txt INTERACTIVE USE THESE MIRRORS ... ok
test_txt_help_arg_api_get_branch (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API GET BRANCH ... ok
test_txt_help_arg_api_prefix (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API PREFIX ... ok
test_txt_help_arg_api_protocols (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API PROTOCOLS ... ok
test_txt_help_arg_api_re_branch (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API REBRANCH ... ok
test_txt_help_arg_api_set_branch (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API SET BRANCH ... ok
test_txt_help_arg_api_url (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG API URL ... ok
test_txt_help_arg_branch (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG BRANCH ... ok
test_txt_help_arg_country (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG COUNTRY ... ok
test_txt_help_arg_default (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG DEFAULT ... ok
test_txt_help_arg_fasttrack (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG FASTTRACK ... ok
test_txt_help_arg_generate (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG GENERATE ... ok
test_txt_help_arg_geoip (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG GEOIP ... ok
test_txt_help_arg_list (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG LIST ... ok
test_txt_help_arg_method (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG METHOD ... ok
test_txt_help_arg_mirrorlist (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG MIRRORLIST ... ok
test_txt_help_arg_quiet (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG QUIET ... ok
test_txt_help_arg_sync (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG SYNC ... ok
test_txt_help_arg_timeout (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG TIMEOUT ... ok
test_txt_help_arg_version (tests.test_txt_help_arg_messages.TestTextHelpArgMessages)
TEST: txt HELP ARG VERSION ... ok
test_txt_error_type_http_exception (tests.test_txt_error_types.TestTextErrorTypes)
TEST: txt ERROR TYPE HTTP EXCEPTION ... ok
test_txt_error_type_timeout (tests.test_txt_error_types.TestTextErrorTypes)
TEST: txt ERROR TYPE TIMEOUT ... ok
test_geoip_available (tests.test_httpfn.TestHttpFn)
TEST: geoip country IS avaiable ... ok
test_txt_api_arguments_error (tests.test_txt_messages.TestTextMessages)
TEST: txt API_ARGUMENTS_ERROR ... ok
test_txt_interactive_arguments_error (tests.test_txt_messages.TestTextMessages)
TEST: txt API_INTERACTIVE_ERROR ... ok
test_txt_msg_api_conf_protocols (tests.test_txt_messages.TestTextMessages)
TEST: txt API CONF PROTOCOLS ... ok
test_txt_msg_api_conf_rebranch (tests.test_txt_messages.TestTextMessages)
TEST: txt API CONF REBRANCH ... ok
test_txt_msg_api_mirrorlist_rebranch (tests.test_txt_messages.TestTextMessages)
TEST: txt API MIRRORLIST REBRANCH ... ok
test_txt_msg_available_countries (tests.test_txt_messages.TestTextMessages)
TEST: txt AVAAILABLE COUNTRIES ... ok
test_txt_msg_cannot_read_file (tests.test_txt_messages.TestTextMessages)
TEST: txt CANNOT READ FILE ... ok
test_txt_msg_cannot_write_file (tests.test_txt_messages.TestTextMessages)
TEST: txt CANNOT WRITE FILE ... ok
test_txt_msg_convert_custom_mirror_file (tests.test_txt_messages.TestTextMessages)
TEST: txt CONVERT CUSTOM MIRROR FILE ... ok
test_txt_msg_custom_mirror_file (tests.test_txt_messages.TestTextMessages)
TEST: txt CUSTOM MIRROR FILE ... ok
test_txt_msg_custom_mirror_file_saved (tests.test_txt_messages.TestTextMessages)
TEST: txt CUSTOM MIRROR FILE SAVED ... ok
test_txt_msg_custom_mirror_list (tests.test_txt_messages.TestTextMessages)
TEST: txt CUSTOM MIRROR LIST ... ok
test_txt_msg_deprecated_argument (tests.test_txt_messages.TestTextMessages)
TEST: txt DEPRECATED ARGUMENT ... ok
test_txt_msg_does_not_exist (tests.test_txt_messages.TestTextMessages)
TEST: txt DOES NOT EXIST ... ok
test_txt_msg_download_file (tests.test_txt_messages.TestTextMessages)
TEST: txt DOWNLOAD FILE ... ok
test_txt_msg_downloading_mirror_file (tests.test_txt_messages.TestTextMessages)
TEST: txt DOWNLOADING MIRROR FILE ... ok
test_txt_msg_falling_back (tests.test_txt_messages.TestTextMessages)
TEST: txt FALLING BACK ... ok
test_txt_msg_internet_alternative (tests.test_txt_messages.TestTextMessages)
TEST: txt INTERNET ALTERNATIVE ... ok
test_txt_msg_internet_down (tests.test_txt_messages.TestTextMessages)
TEST: txt INTERNET DOWN ... ok
test_txt_msg_is_missing (tests.test_txt_messages.TestTextMessages)
TEST: txt IS MISSING ... ok
test_txt_msg_mirror_file (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR FILE ... ok
test_txt_msg_mirror_list_custom_header (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR_LIST_CUSTOM_HEADER ... ok
test_txt_msg_mirror_list_custom_reset (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR_LIST_CUSTOM_RESET ... ok
test_txt_msg_mirror_list_default_header (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR_LIST_DEFAULT_HEADER ... ok
test_txt_msg_mirror_list_default_modify (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR_LIST_DEFAULT_MODIFY ... ok
test_txt_msg_mirror_list_generated_on (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR_LIST_GENERATED_ON ... ok
test_txt_msg_mirror_list_saved (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR LIST SAVED ... ok
test_txt_msg_mirror_ranking_na (tests.test_txt_messages.TestTextMessages)
TEST: txt MIRROR RANKING NA ... ok
test_txt_msg_modify_custom (tests.test_txt_messages.TestTextMessages)
TEST: txt MODIFY_CUSTOM ... ok
test_txt_msg_modify_default (tests.test_txt_messages.TestTextMessages)
TEST: txt MODIFY_DEFAULT ... ok
test_txt_msg_must_be_root (tests.test_txt_messages.TestTextMessages)
TEST: txt MUST BE ROOT ... ok
test_txt_msg_no_change (tests.test_txt_messages.TestTextMessages)
TEST: txt NO CHANGE ... ok
test_txt_msg_no_selection (tests.test_txt_messages.TestTextMessages)
TEST: txt NO SELECTION ... ok
test_txt_msg_option (tests.test_txt_messages.TestTextMessages)
TEST: txt OPTION ... ok
test_txt_msg_please_use (tests.test_txt_messages.TestTextMessages)
TEST: txt PLEASE USE ... ok
test_txt_msg_query_mirrors (tests.test_txt_messages.TestTextMessages)
TEST: txt QUERY MIRRORS ... ok
test_txt_msg_randomizing_servers (tests.test_txt_messages.TestTextMessages)
TEST: txt RANDOMIZING SERVERS ... ok
test_txt_msg_remove_custom_config (tests.test_txt_messages.TestTextMessages)
TEST: txt REMOVE CUSTOM CONFIG ... ok
test_txt_msg_takes_time (tests.test_txt_messages.TestTextMessages)
TEST: txt TAKES TIME ... ok
test_txt_msg_unknown_country (tests.test_txt_messages.TestTextMessages)
TEST: txt UNKNOWN COUNTRY ... ok
test_txt_msg_use_zero_for_all (tests.test_txt_messages.TestTextMessages)
TEST: txt USE_ZERO_FOR_ALL ... ok
test_txt_msg_using_all_mirrors (tests.test_txt_messages.TestTextMessages)
TEST: txt USING ALL MIRRORS ... ok
test_txt_msg_using_custom_file (tests.test_txt_messages.TestTextMessages)
TEST: txt USING CUSTOM FILE ... ok
test_txt_msg_using_default_file (tests.test_txt_messages.TestTextMessages)
TEST: txt USING DEFAULT FILE ... ok
test_txt_msg_writing_mirror_list (tests.test_txt_messages.TestTextMessages)
TEST: txt WRITING MIRROR LIST ... ok
test_txt_msg_type_error (tests.test_txt_message_types.TestTextMessageTypes)
TEST: txt MESSAGE TYPE ERROR ... ok
test_txt_msg_type_info (tests.test_txt_message_types.TestTextMessageTypes)
TEST: txt MESSAGE TYPE INFO ... ok
test_txt_msg_type_warn (tests.test_txt_message_types.TestTextMessageTypes)
TEST: txt MESSAGE TYPE WARN ... ok

----------------------------------------------------------------------
Ran 137 tests in 156.042s

OK
::INFO Downloading mirrors from repo.manjaro.org
::INFO Using default mirror file
::INFO Querying mirrors - This may take some time
  0.3220 :: United_Kingdom  - https://www.mirrorservice.org/sites/repo.manjaro.org/repos/
  0.4400 :: Netherlands     - https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/
  0.2450 :: United_Kingdom  - http://manjaro.mirrors.uk2.net/
  1.9890 :: Australia       - http://manjaro.melbourneitmirror.net/
  2.0060 :: Taiwan          - http://free.nchc.org.tw/manjaro/
  1.7390 :: Japan           - http://ftp.riken.jp/Linux/manjaro/
  2.6460 :: Netherlands     - ftp://ftp.nluug.nl/pub/os/Linux/distr/manjaro/
  0.3710 :: Poland          - http://mirror.tuchola-dc.pl/manjaro/
  0.5300 :: Poland          - https://mirror.tuchola-dc.pl/manjaro/
  0.9130 :: United_States   - https://mirrors.gigenet.com/manjaro/
  0.8300 :: United_States   - http://mirrors.gigenet.com/manjaro/
  5.4380 :: Japan           - ftp://ftp.riken.jp/Linux/manjaro/
  0.3610 :: Greece          - http://ftp.cc.uoc.gr/mirrors/linux/manjaro/
  0.4840 :: Greece          - https://ftp.cc.uoc.gr/mirrors/linux/manjaro/
  0.6700 :: Sweden          - https://ftp.lysator.liu.se/pub/manjaro/
  2.0820 :: United_Kingdom  - http://repo.manjaro.org.uk/
  2.9280 :: Greece          - ftp://ftp.cc.uoc.gr/mirrors/linux/manjaro/
  3.0750 :: Sweden          - ftp://ftp.lysator.liu.se/pub/manjaro/
  7.8390 :: Kenya           - http://manjaro.mirror.liquidtelecom.com/
  5.6070 :: Italy           - https://ct.mirror.garr.it/mirrors/manjaro/
  11.184 :: Kenya           - https://manjaro.mirror.liquidtelecom.com/
  152.303 :: Iran            - http://repo.sadjad.ac.ir/manjaro/
  152.629 :: Iran            - https://repo.sadjad.ac.ir/manjaro/
::INFO Writing mirror list
::United_Kingdom  : https://www.mirrorservice.org/sites/repo.manjaro.org/repos/sta
::United_Kingdom  : http://manjaro.mirrors.uk2.net/stable
::Australia       : http://manjaro.melbourneitmirror.net/stable
::Taiwan          : http://free.nchc.org.tw/manjaro/stable
::INFO Mirror list generated and saved to: tests/mock/etc/mirrorlist
::INFO Downloading mirrors from repo.manjaro.org
::WARNING No mirrors in selection
::INFO The mirrors has not changed
::INFO Downloading mirrors from repo.manjaro.org
::WARNING No mirrors in selection
::INFO The mirrors has not changed
```

### CODE REVIEW

**Comment by fhdk** [comment]
@ZenTauro 
It looks good :+1: 
@papajoker 
Thank you being here too :smile:

**Comment by ZenTauro** [comment]
Thanks :)

After some testing, I realized that this
> pacman-mirrors -f x when 5 < x < 15 it sometimes gets stuck

is caused when it starts a petition to a server that takes a really long time to reply. Even after setting a timeout smaller than the time it takes to poll.

**Comment by fhdk** [comment]
I have build a pacman-mirrors-dev package 4.15.0.dev5 which has been pushed to unstable.

I have made some very small changes to your code and to mine.

I seems to be working - also with the issue you mention.

Could you please test it too?

**Comment by ZenTauro** [comment]
I've been testing the issue and it seems that whenever it starts probing a mirror that takes a long time to answer, it gets blocked until it gets the answer. Even if the request times out.

It gets mitigated when there are a large number of workers, but that increases the probability to poll one of those servers. I think that the best way to fix this is implementing a blacklist functionality, so that users can choose which servers to exclude.

**Comment by fhdk** [comment]
The major problem is when a mirror exhibits such behavior it often comes out of the blue and making it impossible to predict and thus blacklist.

While the idea of threading pacman-mirrors to make the system more responsive also has another back draw - at least for the fasttrack argument - essentially meaning the threaded tasks are still running when the function exits without returning mirrors - printing the message **No mirrors in pool - no change to mirrorlist**.

I have modified the build_pool function to leave out mirrors with the status for either branch or server is -1 which eliminates several potential lock-ups but the problem still persist if the user chooses the --no-status argument - which has the potential to completely gooboo the whole process.

**Pull request merged**
